import Link from 'next/link';
import {
  ArrowUpRight,
  Calendar,
  CheckCircle2,
  ShieldAlert,
  AlertOctagon,
  Stethoscope,
  Banknote,
  Landmark,
  Scale,
  Layers,
  PlayCircle,
} from 'lucide-react';
import { MarketingHeader } from '@/components/marketing/Header';
import { HeaderAuthChip } from '@/components/marketing/HeaderAuth';
import { listShowcases, type ShowcaseRow } from '@/lib/demo/queries';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'See AssuredAI verify content live · AssuredAI',
  description:
    'Click any vertical pack — see a real verification run end-to-end with a hash-chained audit log. Book a 30-minute demo when you’re ready to bring it to your team.',
};

const PACK_ICON: Record<string, React.ComponentType<{ className?: string }>> = {
  healthcare: Stethoscope,
  government: Landmark,
  finance: Banknote,
  legal: Scale,
};

const TONE_TILES: Record<ShowcaseRow['tone'], { border: string; badgeBg: string; label: string; icon: React.ComponentType<{ className?: string }> }> = {
  positive: {
    border: 'border-emerald-200',
    badgeBg: 'bg-emerald-100 text-emerald-700 ring-emerald-200',
    label: 'Publish-ready',
    icon: CheckCircle2,
  },
  warning: {
    border: 'border-amber-200',
    badgeBg: 'bg-amber-100 text-amber-800 ring-amber-200',
    label: 'Caught + redacted',
    icon: ShieldAlert,
  },
  critical: {
    border: 'border-red-200',
    badgeBg: 'bg-red-100 text-red-700 ring-red-200',
    label: 'Blocked at the door',
    icon: AlertOctagon,
  },
};

const PACK_BLURB: Record<string, string> = {
  healthcare:
    'HIPAA-aware editorial verification for patient-facing health content. PHI Safe-Harbor recognizers, cardiac / mental-health / overdose escalation, FDA + CDC disclaimers.',
  government:
    'Plain-language verification for state, federal, and municipal publishers. FedRAMP-aligned recognizers, Section 508 disclaimers, crisis-line routing.',
  finance:
    'SEC / FINRA / SOX / PCI-DSS-aware editorial verification. Credit-card + bank + ITIN recognizers, fraud-language detection, mandatory risk disclaimers.',
  legal:
    'ABA Model Rules + privilege-aware editorial verification. Client PII detection, imminent-harm escalation per Rule 1.6(b), mandatory attorney-client disclaimer.',
};

export default async function DemoPage() {
  const showcases = await listShowcases();
  const byPack = new Map<string, ShowcaseRow[]>();
  for (const s of showcases) {
    if (!byPack.has(s.pack_slug)) byPack.set(s.pack_slug, []);
    byPack.get(s.pack_slug)!.push(s);
  }
  const packs = Array.from(byPack.keys()).sort();

  return (
    <div className="relative min-h-screen bg-background">
      <MarketingHeader authChip={<HeaderAuthChip />} />

      <main>
        {/* Hero */}
        <section className="relative mx-auto max-w-[1240px] px-5 pb-12 pt-16 sm:pt-20">
          <div className="text-[12px] font-semibold uppercase tracking-[0.22em] text-foreground/60">
            Live demo
          </div>
          <h1 className="mt-3 text-balance text-[44px] sm:text-[60px] font-semibold leading-[1.02] tracking-[-0.03em]">
            Watch AssuredAI catch the things you wish your{' '}
            <span className="font-serif italic font-normal text-primary">last AI rollout</span> had
            caught.
          </h1>
          <p className="mt-5 max-w-2xl text-[17px] leading-relaxed text-foreground/75">
            Pick a vertical below. Every card opens a real, live{' '}
            <code className="rounded bg-muted/40 px-1.5 py-0.5 font-mono text-[14px]">/v/&lt;id&gt;</code>{' '}
            proof page generated by our own pipeline — the same hash-chained audit row we&rsquo;d
            give your compliance team. When you&rsquo;re ready to bring it to your stack, book a
            30-minute working session.
          </p>

          <div className="mt-7 flex flex-wrap items-center gap-3">
            <Link
              href="/chat"
              className="group inline-flex h-12 items-center gap-2 rounded-md bg-foreground px-6 text-[14px] font-medium text-background transition-opacity hover:opacity-90"
            >
              <PlayCircle className="h-4 w-4" />
              Try the verifier yourself
              <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
            <Link
              href="/book-a-demo"
              className="inline-flex h-12 items-center gap-2 rounded-md border border-border bg-card px-6 text-[14px] font-medium text-foreground transition-colors hover:bg-accent"
            >
              <Calendar className="h-4 w-4" />
              Book a 30-min working session
            </Link>
          </div>
        </section>

        {/* Per-pack sections */}
        <section className="mx-auto max-w-[1240px] px-5 pb-24">
          {packs.length === 0 && (
            <div className="rounded-2xl border border-border bg-muted/20 px-6 py-16 text-center text-foreground/70">
              <Layers className="mx-auto mb-3 h-6 w-6 opacity-60" />
              No showcase verifications seeded yet — they&rsquo;ll appear here on the next deploy.
            </div>
          )}
          {packs.map((pack) => {
            const Icon = PACK_ICON[pack] ?? Layers;
            const items = byPack.get(pack) ?? [];
            return (
              <div key={pack} className="mt-16 first:mt-0">
                <div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between sm:gap-6">
                  <div>
                    <div className="inline-flex items-center gap-2 text-[12px] font-semibold uppercase tracking-[0.18em] text-foreground/60">
                      <Icon className="h-3.5 w-3.5" />
                      {pack}
                    </div>
                    <h2 className="mt-2 text-[26px] font-semibold tracking-tight">
                      What {pack} verification looks like
                    </h2>
                    <p className="mt-2 max-w-2xl text-[14px] leading-relaxed text-foreground/70">
                      {PACK_BLURB[pack] ?? `Verification configured for the ${pack} vertical.`}
                    </p>
                  </div>
                  <Link
                    href={`/chat?scenario=${pack}`}
                    className="inline-flex h-10 shrink-0 items-center gap-1.5 rounded-md border border-border bg-card px-4 text-[12.5px] font-medium text-foreground transition-colors hover:bg-accent"
                  >
                    Try a {pack} verification
                    <ArrowUpRight className="h-3 w-3" />
                  </Link>
                </div>
                <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                  {items.map((s) => {
                    const t = TONE_TILES[s.tone];
                    const Badge = t.icon;
                    return (
                      <Link
                        key={s.slug}
                        href={`/v/${s.audit_log_id}`}
                        className={`group flex flex-col rounded-2xl border ${t.border} bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-md`}
                      >
                        <div className="flex items-start justify-between gap-3">
                          <span
                            className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-semibold ring-1 ${t.badgeBg}`}
                          >
                            <Badge className="h-3 w-3" />
                            {t.label}
                          </span>
                          <ArrowUpRight className="h-4 w-4 text-foreground/40 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-foreground" />
                        </div>
                        <h3 className="mt-3 text-[17px] font-semibold leading-tight tracking-tight text-foreground">
                          {s.title}
                        </h3>
                        <p className="mt-2 flex-1 text-[13px] leading-relaxed text-foreground/75">
                          {s.blurb}
                        </p>
                        <div className="mt-4 flex items-center justify-between text-[11.5px] text-muted-foreground">
                          <span className="font-mono">audit #{s.audit_log_id}</span>
                          <span>hash-chained · tamper-evident</span>
                        </div>
                      </Link>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </section>

        {/* Book-a-demo CTA */}
        <section className="border-t border-border bg-muted/20 py-20">
          <div className="mx-auto max-w-[860px] px-5 text-center">
            <Calendar className="mx-auto h-7 w-7 text-foreground/70" />
            <h2 className="mt-4 text-balance text-[34px] sm:text-[40px] font-semibold leading-tight tracking-tight">
              30 minutes. We bring your{' '}
              <span className="font-serif italic font-normal text-primary">real content</span>.
            </h2>
            <p className="mt-4 text-[15.5px] leading-relaxed text-foreground/75">
              Send us 3–5 representative articles from your team — patient handouts, financial
              explainers, policy briefs, whatever you publish — and we&rsquo;ll run them live on
              the call. You walk away with a private proof URL for each one and a written
              compliance assessment.
            </p>
            <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
              <Link
                href="/book-a-demo"
                className="inline-flex h-12 items-center gap-2 rounded-md bg-foreground px-6 text-[14px] font-semibold text-background hover:opacity-90"
              >
                <Calendar className="h-4 w-4" />
                Book a working session
              </Link>
              <Link
                href="/talk-to-sales"
                className="inline-flex h-12 items-center gap-2 rounded-md border border-border bg-card px-6 text-[14px] font-medium text-foreground hover:bg-accent"
              >
                Talk to sales
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
