import Link from 'next/link';
import {
  ArrowUpRight,
  ShieldAlert,
  CheckCircle2,
  AlertOctagon,
  Layers,
  Stethoscope,
  Landmark,
  Scale,
  Banknote,
} from 'lucide-react';
import { listShowcases, type ShowcaseRow } from '@/lib/demo/queries';

const PACK_ICON: Record<string, React.ComponentType<{ className?: string }>> = {
  healthcare: Stethoscope,
  government: Landmark,
  finance: Banknote,
  legal: Scale,
};

const TONE_STYLES: Record<ShowcaseRow['tone'], string> = {
  positive: 'border-emerald-200 bg-emerald-50/40 text-emerald-900',
  warning: 'border-amber-200 bg-amber-50/50 text-amber-900',
  critical: 'border-red-200 bg-red-50/50 text-red-900',
};

const TONE_BADGE: Record<ShowcaseRow['tone'], { bg: string; label: string; icon: React.ComponentType<{ className?: string }> }> = {
  positive: {
    bg: 'bg-emerald-100 text-emerald-700 ring-emerald-200',
    label: 'Publish-ready',
    icon: CheckCircle2,
  },
  warning: {
    bg: 'bg-amber-100 text-amber-800 ring-amber-200',
    label: 'Caught + redacted',
    icon: ShieldAlert,
  },
  critical: {
    bg: 'bg-red-100 text-red-700 ring-red-200',
    label: 'Blocked at the door',
    icon: AlertOctagon,
  },
};

/**
 * Marketing showcase — server component that lists real, live audit
 * URLs for visitors to click into. Each card is a one-click proof that
 * the platform actually works as described, sourced from the seed-run
 * showcase verifications.
 */
export async function ShowcaseStrip() {
  const showcases = await listShowcases();
  if (showcases.length === 0) return null;

  return (
    <section
      id="showcase"
      className="mx-auto max-w-[1240px] px-5 py-20 sm:py-28"
    >
      <header className="mb-10 max-w-3xl">
        <div className="text-[12px] font-semibold uppercase tracking-[0.22em] text-foreground/60">
          Real verifications · click any card
        </div>
        <h2 className="mt-3 text-[34px] sm:text-[40px] font-semibold leading-tight tracking-tight">
          Every claim on this site is{' '}
          <span className="font-serif italic font-normal text-primary">a real proof URL</span>.
        </h2>
        <p className="mt-4 max-w-2xl text-[15.5px] leading-relaxed text-foreground/75">
          These aren&rsquo;t demo screenshots. Each card below opens a live{' '}
          <code className="rounded bg-muted/40 px-1.5 py-0.5 font-mono text-[12.5px]">/v/&lt;id&gt;</code>{' '}
          proof page generated by our own pipeline, hash-chained into the same audit log we&rsquo;d
          give your compliance team. Pick a vertical — see the platform do the work.
        </p>
      </header>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {showcases.map((s) => {
          const Icon = PACK_ICON[s.pack_slug] ?? Layers;
          const tone = TONE_STYLES[s.tone];
          const badge = TONE_BADGE[s.tone];
          const Badge = badge.icon;
          return (
            <Link
              key={s.slug}
              href={`/v/${s.audit_log_id}`}
              className={`group relative flex flex-col rounded-2xl border ${tone} p-5 transition-all hover:-translate-y-0.5 hover:shadow-md`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-foreground/70">
                  <Icon className="h-3 w-3" />
                  {s.pack_slug}
                </div>
                <ArrowUpRight className="h-4 w-4 text-foreground/40 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-foreground" />
              </div>
              <h3 className="mt-3 text-[18px] font-semibold leading-tight tracking-tight text-foreground">
                {s.title}
              </h3>
              <p className="mt-2 flex-1 text-[13.5px] leading-relaxed text-foreground/75">
                {s.blurb}
              </p>
              <div className="mt-4 flex items-center justify-between gap-2 text-[11.5px]">
                <span
                  className={`inline-flex items-center gap-1 rounded-full px-2 py-1 font-semibold ring-1 ${badge.bg}`}
                >
                  <Badge className="h-3 w-3" />
                  {badge.label}
                </span>
                <span className="font-mono text-foreground/55">/v/{s.audit_log_id}</span>
              </div>
            </Link>
          );
        })}
      </div>
    </section>
  );
}
